### ISSUE TITLE
Consider the drake R package.

### ISSUE THREAD

**Issue by wlandau-lilly** [bdcaf/coockiecutter-r-data-analysis#1]
Since you mention Make, I suggest considering the [drake R package](https://github.com/wlandau-lilly/drake), [documented more here](https://wlandau-lilly.github.io/drake). (Full disclosure: I am the maintainer.) Relative to Make, [drake](https://github.com/wlandau-lilly/drake) is much easier to use from R, and it is more scalable for projects with a large number of targets. Until the review process at ropensci/onboarding#156 is complete, I recommend using the development version.

**Comment by bdcaf** [comment]
I had a look on drake some time ago. Then the documentation was very lacking and I found it particularly unintuitive to run command line tools.  I will check it out again.

**Comment by bdcaf** [comment]
Well - after some testing I don't get too warm with it. I just feel more comfortable with Makefiles with all their baggage.   It is definitely something to look out for but I feel for my projects it adds more overhead than benefit.
